// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
    user_id,
    filename,
    original_filename,
    mime_type,
    size_bytes,
    storage_path,
    storage_backend,
    checksum,
    width,
    height,
    metadata
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11
) RETURNING id, user_id, filename, original_filename, mime_type, size_bytes, storage_path, storage_backend, checksum, width, height, metadata, created_at
`

type CreateAssetParams struct {
	UserID           string `json:"user_id"`
	Filename         string `json:"filename"`
	OriginalFilename string `json:"original_filename"`
	MimeType         string `json:"mime_type"`
	SizeBytes        int32  `json:"size_bytes"`
	StoragePath      string `json:"storage_path"`
	StorageBackend   string `json:"storage_backend"`
	Checksum         string `json:"checksum"`
	Width            *int32 `json:"width"`
	Height           *int32 `json:"height"`
	Metadata         []byte `json:"metadata"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.UserID,
		arg.Filename,
		arg.OriginalFilename,
		arg.MimeType,
		arg.SizeBytes,
		arg.StoragePath,
		arg.StorageBackend,
		arg.Checksum,
		arg.Width,
		arg.Height,
		arg.Metadata,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.StorageBackend,
		&i.Checksum,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAsset = `-- name: DeleteAsset :exec
DELETE FROM assets WHERE id = $1
`

func (q *Queries) DeleteAsset(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAsset, id)
	return err
}

const deleteAssetsByUserID = `-- name: DeleteAssetsByUserID :exec
DELETE FROM assets WHERE user_id = $1
`

func (q *Queries) DeleteAssetsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAssetsByUserID, userID)
	return err
}

const getAssetByChecksum = `-- name: GetAssetByChecksum :one
SELECT id, user_id, filename, original_filename, mime_type, size_bytes, storage_path, storage_backend, checksum, width, height, metadata, created_at FROM assets 
WHERE user_id = $1 AND checksum = $2
`

type GetAssetByChecksumParams struct {
	UserID   string `json:"user_id"`
	Checksum string `json:"checksum"`
}

func (q *Queries) GetAssetByChecksum(ctx context.Context, arg GetAssetByChecksumParams) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByChecksum, arg.UserID, arg.Checksum)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.StorageBackend,
		&i.Checksum,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT id, user_id, filename, original_filename, mime_type, size_bytes, storage_path, storage_backend, checksum, width, height, metadata, created_at FROM assets WHERE id = $1
`

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Filename,
		&i.OriginalFilename,
		&i.MimeType,
		&i.SizeBytes,
		&i.StoragePath,
		&i.StorageBackend,
		&i.Checksum,
		&i.Width,
		&i.Height,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getTotalAssetSizeByUserID = `-- name: GetTotalAssetSizeByUserID :one
SELECT COALESCE(SUM(size_bytes), 0)::bigint as total_size
FROM assets 
WHERE user_id = $1
`

func (q *Queries) GetTotalAssetSizeByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, getTotalAssetSizeByUserID, userID)
	var total_size int64
	err := row.Scan(&total_size)
	return total_size, err
}

const listAssetsByUserID = `-- name: ListAssetsByUserID :many
SELECT id, user_id, filename, original_filename, mime_type, size_bytes, storage_path, storage_backend, checksum, width, height, metadata, created_at FROM assets 
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListAssetsByUserID(ctx context.Context, userID string) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Asset{}
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Filename,
			&i.OriginalFilename,
			&i.MimeType,
			&i.SizeBytes,
			&i.StoragePath,
			&i.StorageBackend,
			&i.Checksum,
			&i.Width,
			&i.Height,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
