// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: cvs.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
)

const countCVsByUserID = `-- name: CountCVsByUserID :one
SELECT COUNT(*) FROM cvs WHERE user_id = $1
`

func (q *Queries) CountCVsByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countCVsByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createCV = `-- name: CreateCV :one
INSERT INTO cvs (
    user_id,
    title,
    schema_version,
    content
) VALUES (
    $1, $2, $3, $4
) RETURNING id, user_id, title, schema_version, content, is_active, created_at, updated_at
`

type CreateCVParams struct {
	UserID        string          `json:"user_id"`
	Title         string          `json:"title"`
	SchemaVersion string          `json:"schema_version"`
	Content       json.RawMessage `json:"content"`
}

func (q *Queries) CreateCV(ctx context.Context, arg CreateCVParams) (Cv, error) {
	row := q.db.QueryRow(ctx, createCV,
		arg.UserID,
		arg.Title,
		arg.SchemaVersion,
		arg.Content,
	)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SchemaVersion,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCV = `-- name: DeleteCV :exec
DELETE FROM cvs WHERE id = $1
`

func (q *Queries) DeleteCV(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteCV, id)
	return err
}

const deleteCVsByUserID = `-- name: DeleteCVsByUserID :exec
DELETE FROM cvs WHERE user_id = $1
`

func (q *Queries) DeleteCVsByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteCVsByUserID, userID)
	return err
}

const getCVByID = `-- name: GetCVByID :one
SELECT id, user_id, title, schema_version, content, is_active, created_at, updated_at FROM cvs WHERE id = $1
`

func (q *Queries) GetCVByID(ctx context.Context, id uuid.UUID) (Cv, error) {
	row := q.db.QueryRow(ctx, getCVByID, id)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SchemaVersion,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCVByUserID = `-- name: GetCVByUserID :one
SELECT id, user_id, title, schema_version, content, is_active, created_at, updated_at FROM cvs 
WHERE user_id = $1 AND is_active = true
ORDER BY updated_at DESC
LIMIT 1
`

// Gets the user's active CV (for single-CV users)
func (q *Queries) GetCVByUserID(ctx context.Context, userID string) (Cv, error) {
	row := q.db.QueryRow(ctx, getCVByUserID, userID)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SchemaVersion,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listCVsByUserID = `-- name: ListCVsByUserID :many
SELECT id, user_id, title, schema_version, content, is_active, created_at, updated_at FROM cvs 
WHERE user_id = $1
ORDER BY updated_at DESC
`

func (q *Queries) ListCVsByUserID(ctx context.Context, userID string) ([]Cv, error) {
	rows, err := q.db.Query(ctx, listCVsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Cv{}
	for rows.Next() {
		var i Cv
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.SchemaVersion,
			&i.Content,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setCVActive = `-- name: SetCVActive :exec
UPDATE cvs SET
    is_active = $2,
    updated_at = NOW()
WHERE id = $1
`

type SetCVActiveParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive *bool     `json:"is_active"`
}

func (q *Queries) SetCVActive(ctx context.Context, arg SetCVActiveParams) error {
	_, err := q.db.Exec(ctx, setCVActive, arg.ID, arg.IsActive)
	return err
}

const updateCV = `-- name: UpdateCV :one
UPDATE cvs SET
    title = COALESCE($2, title),
    content = COALESCE($3, content),
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, schema_version, content, is_active, created_at, updated_at
`

type UpdateCVParams struct {
	ID      uuid.UUID       `json:"id"`
	Title   string          `json:"title"`
	Content json.RawMessage `json:"content"`
}

func (q *Queries) UpdateCV(ctx context.Context, arg UpdateCVParams) (Cv, error) {
	row := q.db.QueryRow(ctx, updateCV, arg.ID, arg.Title, arg.Content)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SchemaVersion,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCVContent = `-- name: UpdateCVContent :one
UPDATE cvs SET
    content = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, user_id, title, schema_version, content, is_active, created_at, updated_at
`

type UpdateCVContentParams struct {
	ID      uuid.UUID       `json:"id"`
	Content json.RawMessage `json:"content"`
}

func (q *Queries) UpdateCVContent(ctx context.Context, arg UpdateCVContentParams) (Cv, error) {
	row := q.db.QueryRow(ctx, updateCVContent, arg.ID, arg.Content)
	var i Cv
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.SchemaVersion,
		&i.Content,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
