// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: export_jobs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createExportJob = `-- name: CreateExportJob :one
INSERT INTO export_jobs (
    user_id,
    cv_id,
    format,
    status
) VALUES (
    $1, $2, $3, 'pending'
) RETURNING id, user_id, cv_id, format, status, result_path, error_message, created_at, started_at, completed_at
`

type CreateExportJobParams struct {
	UserID string    `json:"user_id"`
	CvID   uuid.UUID `json:"cv_id"`
	Format string    `json:"format"`
}

func (q *Queries) CreateExportJob(ctx context.Context, arg CreateExportJobParams) (ExportJob, error) {
	row := q.db.QueryRow(ctx, createExportJob, arg.UserID, arg.CvID, arg.Format)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CvID,
		&i.Format,
		&i.Status,
		&i.ResultPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const deleteOldExportJobs = `-- name: DeleteOldExportJobs :exec
DELETE FROM export_jobs
WHERE completed_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) DeleteOldExportJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteOldExportJobs)
	return err
}

const getExportJobByID = `-- name: GetExportJobByID :one
SELECT id, user_id, cv_id, format, status, result_path, error_message, created_at, started_at, completed_at FROM export_jobs WHERE id = $1
`

func (q *Queries) GetExportJobByID(ctx context.Context, id uuid.UUID) (ExportJob, error) {
	row := q.db.QueryRow(ctx, getExportJobByID, id)
	var i ExportJob
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.CvID,
		&i.Format,
		&i.Status,
		&i.ResultPath,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.StartedAt,
		&i.CompletedAt,
	)
	return i, err
}

const listExportJobsByUserID = `-- name: ListExportJobsByUserID :many
SELECT id, user_id, cv_id, format, status, result_path, error_message, created_at, started_at, completed_at FROM export_jobs 
WHERE user_id = $1
ORDER BY created_at DESC
LIMIT $2
`

type ListExportJobsByUserIDParams struct {
	UserID string `json:"user_id"`
	Limit  int32  `json:"limit"`
}

func (q *Queries) ListExportJobsByUserID(ctx context.Context, arg ListExportJobsByUserIDParams) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listExportJobsByUserID, arg.UserID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CvID,
			&i.Format,
			&i.Status,
			&i.ResultPath,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingExportJobs = `-- name: ListPendingExportJobs :many
SELECT id, user_id, cv_id, format, status, result_path, error_message, created_at, started_at, completed_at FROM export_jobs 
WHERE status IN ('pending', 'processing')
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) ListPendingExportJobs(ctx context.Context, limit int32) ([]ExportJob, error) {
	rows, err := q.db.Query(ctx, listPendingExportJobs, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExportJob{}
	for rows.Next() {
		var i ExportJob
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.CvID,
			&i.Format,
			&i.Status,
			&i.ResultPath,
			&i.ErrorMessage,
			&i.CreatedAt,
			&i.StartedAt,
			&i.CompletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExportJobStatus = `-- name: UpdateExportJobStatus :exec
UPDATE export_jobs SET
    status = $2,
    result_path = $3,
    error_message = $4,
    started_at = CASE WHEN $2 = 'processing' THEN NOW() ELSE started_at END,
    completed_at = CASE WHEN $2 IN ('completed', 'failed') THEN NOW() ELSE completed_at END
WHERE id = $1
`

type UpdateExportJobStatusParams struct {
	ID           uuid.UUID `json:"id"`
	Status       *string   `json:"status"`
	ResultPath   *string   `json:"result_path"`
	ErrorMessage *string   `json:"error_message"`
}

func (q *Queries) UpdateExportJobStatus(ctx context.Context, arg UpdateExportJobStatusParams) error {
	_, err := q.db.Exec(ctx, updateExportJobStatus,
		arg.ID,
		arg.Status,
		arg.ResultPath,
		arg.ErrorMessage,
	)
	return err
}
