// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"encoding/json"
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

// User-uploaded files (portraits, etc.)
type Asset struct {
	ID               uuid.UUID `json:"id"`
	UserID           string    `json:"user_id"`
	Filename         string    `json:"filename"`
	OriginalFilename string    `json:"original_filename"`
	MimeType         string    `json:"mime_type"`
	SizeBytes        int32     `json:"size_bytes"`
	StoragePath      string    `json:"storage_path"`
	StorageBackend   string    `json:"storage_backend"`
	// SHA-256 hash for deduplication and integrity
	Checksum  string             `json:"checksum"`
	Width     *int32             `json:"width"`
	Height    *int32             `json:"height"`
	Metadata  []byte             `json:"metadata"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

// Immutable log of all data mutations
type AuditLog struct {
	ID         int64              `json:"id"`
	UserID     *string            `json:"user_id"`
	Action     string             `json:"action"`
	EntityType string             `json:"entity_type"`
	EntityID   *string            `json:"entity_id"`
	OldValue   []byte             `json:"old_value"`
	NewValue   []byte             `json:"new_value"`
	IpAddress  *netip.Addr        `json:"ip_address"`
	UserAgent  *string            `json:"user_agent"`
	RequestID  *string            `json:"request_id"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
}

// CV documents stored as JSON with schema versioning
type Cv struct {
	ID            uuid.UUID `json:"id"`
	UserID        string    `json:"user_id"`
	Title         string    `json:"title"`
	SchemaVersion string    `json:"schema_version"`
	// CV data following schemas/cv-schema.json
	Content   json.RawMessage    `json:"content"`
	IsActive  *bool              `json:"is_active"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

// Async export job queue for PDF/DOCX generation
type ExportJob struct {
	ID           uuid.UUID          `json:"id"`
	UserID       string             `json:"user_id"`
	CvID         uuid.UUID          `json:"cv_id"`
	Format       string             `json:"format"`
	Status       *string            `json:"status"`
	ResultPath   *string            `json:"result_path"`
	ErrorMessage *string            `json:"error_message"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	StartedAt    pgtype.Timestamptz `json:"started_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

// User accounts linked to external identity providers
type User struct {
	ID            string  `json:"id"`
	ExternalID    string  `json:"external_id"`
	Provider      string  `json:"provider"`
	Email         string  `json:"email"`
	EmailVerified *bool   `json:"email_verified"`
	DisplayName   *string `json:"display_name"`
	// Subscription tier: free (1 CV), pro (5 CVs), power (unlimited)
	Tier *string `json:"tier"`
	// Maximum number of CVs allowed for this user
	CvLimit           *int32             `json:"cv_limit"`
	StorageLimitBytes *int64             `json:"storage_limit_bytes"`
	StorageUsedBytes  *int64             `json:"storage_used_bytes"`
	Locale            *string            `json:"locale"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}
