// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package queries

import (
	"context"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id,
    external_id,
    provider,
    email,
    email_verified,
    display_name,
    tier,
    cv_limit,
    storage_limit_bytes,
    locale
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, external_id, provider, email, email_verified, display_name, tier, cv_limit, storage_limit_bytes, storage_used_bytes, locale, created_at, updated_at
`

type CreateUserParams struct {
	ID                string  `json:"id"`
	ExternalID        string  `json:"external_id"`
	Provider          string  `json:"provider"`
	Email             string  `json:"email"`
	EmailVerified     *bool   `json:"email_verified"`
	DisplayName       *string `json:"display_name"`
	Tier              *string `json:"tier"`
	CvLimit           *int32  `json:"cv_limit"`
	StorageLimitBytes *int64  `json:"storage_limit_bytes"`
	Locale            *string `json:"locale"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.ExternalID,
		arg.Provider,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.Tier,
		arg.CvLimit,
		arg.StorageLimitBytes,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Tier,
		&i.CvLimit,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, external_id, provider, email, email_verified, display_name, tier, cv_limit, storage_limit_bytes, storage_used_bytes, locale, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Tier,
		&i.CvLimit,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByExternalID = `-- name: GetUserByExternalID :one
SELECT id, external_id, provider, email, email_verified, display_name, tier, cv_limit, storage_limit_bytes, storage_used_bytes, locale, created_at, updated_at FROM users WHERE provider = $1 AND external_id = $2
`

type GetUserByExternalIDParams struct {
	Provider   string `json:"provider"`
	ExternalID string `json:"external_id"`
}

func (q *Queries) GetUserByExternalID(ctx context.Context, arg GetUserByExternalIDParams) (User, error) {
	row := q.db.QueryRow(ctx, getUserByExternalID, arg.Provider, arg.ExternalID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Tier,
		&i.CvLimit,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, external_id, provider, email, email_verified, display_name, tier, cv_limit, storage_limit_bytes, storage_used_bytes, locale, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Tier,
		&i.CvLimit,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    email = COALESCE($2, email),
    email_verified = COALESCE($3, email_verified),
    display_name = COALESCE($4, display_name),
    locale = COALESCE($5, locale),
    updated_at = NOW()
WHERE id = $1
RETURNING id, external_id, provider, email, email_verified, display_name, tier, cv_limit, storage_limit_bytes, storage_used_bytes, locale, created_at, updated_at
`

type UpdateUserParams struct {
	ID            string  `json:"id"`
	Email         string  `json:"email"`
	EmailVerified *bool   `json:"email_verified"`
	DisplayName   *string `json:"display_name"`
	Locale        *string `json:"locale"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailVerified,
		arg.DisplayName,
		arg.Locale,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Tier,
		&i.CvLimit,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStorageUsed = `-- name: UpdateUserStorageUsed :exec
UPDATE users SET
    storage_used_bytes = $2,
    updated_at = NOW()
WHERE id = $1
`

type UpdateUserStorageUsedParams struct {
	ID               string `json:"id"`
	StorageUsedBytes *int64 `json:"storage_used_bytes"`
}

func (q *Queries) UpdateUserStorageUsed(ctx context.Context, arg UpdateUserStorageUsedParams) error {
	_, err := q.db.Exec(ctx, updateUserStorageUsed, arg.ID, arg.StorageUsedBytes)
	return err
}

const updateUserTier = `-- name: UpdateUserTier :one
UPDATE users SET
    tier = $2,
    cv_limit = $3,
    storage_limit_bytes = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, external_id, provider, email, email_verified, display_name, tier, cv_limit, storage_limit_bytes, storage_used_bytes, locale, created_at, updated_at
`

type UpdateUserTierParams struct {
	ID                string  `json:"id"`
	Tier              *string `json:"tier"`
	CvLimit           *int32  `json:"cv_limit"`
	StorageLimitBytes *int64  `json:"storage_limit_bytes"`
}

func (q *Queries) UpdateUserTier(ctx context.Context, arg UpdateUserTierParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserTier,
		arg.ID,
		arg.Tier,
		arg.CvLimit,
		arg.StorageLimitBytes,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.ExternalID,
		&i.Provider,
		&i.Email,
		&i.EmailVerified,
		&i.DisplayName,
		&i.Tier,
		&i.CvLimit,
		&i.StorageLimitBytes,
		&i.StorageUsedBytes,
		&i.Locale,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
